// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v3.21.12
// source: Mica.proto

export const protobufPackage = 'obiba.mica';

export enum StateType {
  StateType_UNSET = 'StateType_UNSET',
  STUDY_SUMMARY = 'STUDY_SUMMARY',
  NETWORK = 'NETWORK',
  NETWORK_SUMMARY = 'NETWORK_SUMMARY',
  DATASET = 'DATASET',
  PROJECT = 'PROJECT',
  UNRECOGNIZED = 'UNRECOGNIZED',
}

export enum OpalCredentialType {
  USERNAME = 'USERNAME',
  PUBLIC_KEY_CERTIFICATE = 'PUBLIC_KEY_CERTIFICATE',
  TOKEN = 'TOKEN',
  UNRECOGNIZED = 'UNRECOGNIZED',
}

export enum KeyType {
  KEY_PAIR = 'KEY_PAIR',
  CERTIFICATE = 'CERTIFICATE',
  UNRECOGNIZED = 'UNRECOGNIZED',
}

export enum FileType {
  FILE = 'FILE',
  FOLDER = 'FOLDER',
  UNRECOGNIZED = 'UNRECOGNIZED',
}

export interface SessionDto {
  username: string;
  roles: string[];
}

export interface PermissionsDto {
  add?: boolean | undefined;
  view?: boolean | undefined;
  edit?: boolean | undefined;
  delete?: boolean | undefined;
  publish?: boolean | undefined;
}

export interface StudySummaryDto {
  id: string;
  timestamps?: TimestampsDto | undefined;
  name: LocalizedStringDto[];
  acronym: LocalizedStringDto[];
  design?: string | undefined;
  targetNumber?: TargetNumberDto | undefined;
  countries: string[];
  logo?: AttachmentDto | undefined;
  objectives: LocalizedStringDto[];
  dataSources: string[];
  populationSummaries: PopulationSummaryDto[];
  published: boolean;
  variables?: number | undefined;
  permissions?: PermissionsDto | undefined;
  studyResourcePath?: string | undefined;
  content?: string | undefined;
  state?: EntityStateDto | undefined;
  /** Specific to search */
  countStats?: CountStatsDto | undefined;
}

export interface PopulationSummaryDto {
  id: string;
  name: LocalizedStringDto[];
  dataCollectionEventSummaries: DataCollectionEventSummaryDto[];
  description: LocalizedStringDto[];
  content?: string | undefined;
}

export interface DataCollectionEventSummaryDto {
  id: string;
  name: LocalizedStringDto[];
  description: LocalizedStringDto[];
  content?: string | undefined;
  start?: string | undefined;
  end?: string | undefined;
}

export interface StudiesDto {
  total: number;
  from: number;
  limit: number;
  studies: StudyDto[];
}

export interface StudySummariesDto {
  total: number;
  from: number;
  limit: number;
  studySummaries: StudySummaryDto[];
}

export interface EntityStateDto {
  publishedTag?: string | undefined;
  revisionsAhead: number;
  revisionStatus?: string | undefined;
  publicationDate?: string | undefined;
  publishedBy?: string | undefined;
  publishedId?: string | undefined;
  permissions?: PermissionsDto | undefined;
  requireIndexing?: boolean | undefined;
}

export interface PopulationDto {
  id?: string | undefined;
  name: LocalizedStringDto[];
  description: LocalizedStringDto[];
  dataCollectionEvents: PopulationDto_DataCollectionEventDto[];
  content?: string | undefined;
  weight?: number | undefined;
}

export interface PopulationDto_RecruitmentDto {
  dataSources: string[];
  generalPopulationSources: string[];
  specificPopulationSources: string[];
  otherSpecificPopulationSource: LocalizedStringDto[];
  studies: LocalizedStringDtos[];
  otherSource: LocalizedStringDto[];
  info: LocalizedStringDto[];
}

export interface PopulationDto_SelectionCriteriaDto {
  gender?: PopulationDto_SelectionCriteriaDto_Gender | undefined;
  ageMin?: number | undefined;
  ageMax?: number | undefined;
  countriesIso: string[];
  territory: LocalizedStringDto[];
  criteria: string[];
  ethnicOrigin: LocalizedStringDtos[];
  healthStatus: LocalizedStringDtos[];
  otherCriteria: LocalizedStringDto[];
  info: LocalizedStringDto[];
}

export enum PopulationDto_SelectionCriteriaDto_Gender {
  men = 'men',
  women = 'women',
  UNRECOGNIZED = 'UNRECOGNIZED',
}

export interface PopulationDto_DataCollectionEventDto {
  id?: string | undefined;
  name: LocalizedStringDto[];
  description: LocalizedStringDto[];
  startYear: number;
  startMonth?: number | undefined;
  endYear?: number | undefined;
  endMonth?: number | undefined;
  attachments: AttachmentDto[];
  content?: string | undefined;
  weight?: number | undefined;
  startDay?: string | undefined;
  endDay?: string | undefined;
}

export interface MembershipSortOrderDto {
  role: string;
  personIds: string[];
}

export interface StudyDto {
  id?: string | undefined;
  timestamps?: TimestampsDto | undefined;
  name: LocalizedStringDto[];
  acronym: LocalizedStringDto[];
  logo?: AttachmentDto | undefined;
  objectives: LocalizedStringDto[];
  populations: PopulationDto[];
  opal?: string | undefined;
  permissions?: PermissionsDto | undefined;
  memberships: MembershipsDto[];
  content?: string | undefined;
  published?: boolean | undefined;
  studyResourcePath?: string | undefined;
  membershipSortOrder: MembershipSortOrderDto[];
  attributes: AttributeDto[];
  initiative?: HarmonizationStudyDto | undefined;
}

export interface HarmonizationStudyDto {
  studyTables: DatasetDto_StudyTableDto[];
  harmonizationTables: DatasetDto_HarmonizationTableDto[];
}

export interface OpalCredentialDto {
  type: OpalCredentialType;
  opalUrl: string;
  username?: string | undefined;
  password?: string | undefined;
  keyForm?: KeyForm | undefined;
  token?: string | undefined;
}

export interface KeyDto {
  alias: string;
  certificate: string;
  keyType: KeyType;
}

export interface KeyForm {
  alias?: string | undefined;
  privateForm?: PrivateKeyForm | undefined;
  privateImport?: string | undefined;
  publicForm?: PublicKeyForm | undefined;
  publicImport?: string | undefined;
  certificateFile?: string | undefined;
  keyType: KeyType;
}

export interface PrivateKeyForm {
  algo: string;
  size: number;
}

export interface PublicKeyForm {
  name?: string | undefined;
  organizationalUnit?: string | undefined;
  organization?: string | undefined;
  locality?: string | undefined;
  state?: string | undefined;
  country?: string | undefined;
}

export interface DocumentDigestDto {
  id: string;
  acronym: LocalizedStringDto[];
  name: LocalizedStringDto[];
  /** Specific to network */
  ids: string[];
}

export interface NetworkDto {
  id?: string | undefined;
  timestamps?: TimestampsDto | undefined;
  name: LocalizedStringDto[];
  acronym: LocalizedStringDto[];
  investigators: PersonDto[];
  contacts: PersonDto[];
  description: LocalizedStringDto[];
  attachments: AttachmentDto[];
  studyIds: string[];
  studySummaries: StudySummaryDto[];
  published?: boolean | undefined;
  logo?: AttachmentDto | undefined;
  memberships: MembershipsDto[];
  networkIds: string[];
  networkSummaries: NetworkSummaryDto[];
  permissions?: PermissionsDto | undefined;
  content?: string | undefined;
  membershipSortOrder: MembershipSortOrderDto[];
  state?: EntityStateDto | undefined;
  /** Specific to search */
  countStats?: CountStatsDto | undefined;
}

export interface NetworksDto {
  total: number;
  from: number;
  limit: number;
  networks: NetworkDto[];
}

export interface NetworkSummaryDto {
  id?: string | undefined;
  timestamps?: TimestampsDto | undefined;
  name: LocalizedStringDto[];
  acronym: LocalizedStringDto[];
  published: boolean;
  studyIds: string[];
  networkIds: string[];
  permissions?: PermissionsDto | undefined;
  state?: EntityStateDto | undefined;
}

export interface TimestampsDto {
  created?: string | undefined;
  lastUpdate?: string | undefined;
}

export interface CountryDto {
  iso: string;
  name: LocalizedStringDto[];
}

export interface TargetNumberDto {
  noLimit?: boolean | undefined;
  number?: number | undefined;
}

export interface LocalizedStringDto {
  lang: string;
  value?: string | undefined;
}

export interface LocalizedStringDtos {
  localizedStrings: LocalizedStringDto[];
}

export interface MembershipsDto {
  role: string;
  members: PersonDto[];
}

export interface PersonDto {
  title?: string | undefined;
  firstName?: string | undefined;
  lastName: string;
  academicLevel?: string | undefined;
  email?: string | undefined;
  phone?: string | undefined;
  dataAccessCommitteeMember?: boolean | undefined;
  institution?: PersonDto_InstitutionDto | undefined;
  id?: string | undefined;
  studyMemberships: PersonDto_MembershipDto[];
  networkMemberships: PersonDto_MembershipDto[];
  timestamps?: TimestampsDto | undefined;
}

export enum PersonDto_Type {
  Type_UNSET = 'Type_UNSET',
  STUDY = 'STUDY',
  INITIATIVE = 'INITIATIVE',
  NETWORK = 'NETWORK',
  UNRECOGNIZED = 'UNRECOGNIZED',
}

export interface PersonDto_InstitutionDto {
  name: LocalizedStringDto[];
  department: LocalizedStringDto[];
  address?: AddressDto | undefined;
}

export interface PersonDto_MembershipDto {
  role: string;
  parentId: string;
  parentAcronym: LocalizedStringDto[];
  parentName: LocalizedStringDto[];
  type?: PersonDto_Type | undefined;
}

export interface PersonsDto {
  total: number;
  from: number;
  limit: number;
  persons: PersonDto[];
}

export interface AuthorizationDto {
  authorized?: boolean | undefined;
  authorizer?: string | undefined;
  date?: string | undefined;
}

export interface AddressDto {
  street: LocalizedStringDto[];
  city: LocalizedStringDto[];
  zip?: string | undefined;
  state?: string | undefined;
  country?: CountryDto | undefined;
}

export interface AttachmentDto {
  id: string;
  fileName: string;
  type?: string | undefined;
  description: LocalizedStringDto[];
  lang?: string | undefined;
  size?: number | undefined;
  md5?: string | undefined;
  justUploaded?: boolean | undefined;
  timestamps?: TimestampsDto | undefined;
  attributes: AttributeDto[];
  path?: string | undefined;
  lastModifiedBy?: string | undefined;
}

export interface TempFileDto {
  id: string;
  name: string;
  size?: number | undefined;
  md5?: string | undefined;
}

export interface MicaConfigDto {
  name: string;
  languages: string[];
  defaultCharSet: string;
  publicUrl?: string | undefined;
  opal?: string | undefined;
  version?: string | undefined;
  privacyThreshold?: number | undefined;
  roles: string[];
  openAccess: boolean;
  isFsNotificationsEnabled?: boolean | undefined;
  fsNotificationsSubject?: string | undefined;
  isCommentNotificationsEnabled?: boolean | undefined;
  commentNotificationsSubject?: string | undefined;
  isStudyNotificationsEnabled?: boolean | undefined;
  studyNotificationsSubject?: string | undefined;
  isNetworkNotificationsEnabled?: boolean | undefined;
  networkNotificationsSubject?: string | undefined;
  isCollectedDatasetNotificationsEnabled?: boolean | undefined;
  collectedDatasetNotificationsSubject?: string | undefined;
  isHarmonizedDatasetNotificationsEnabled?: boolean | undefined;
  harmonizedDatasetNotificationsSubject?: string | undefined;
  isSingleStudyEnabled?: boolean | undefined;
  isNetworkEnabled?: boolean | undefined;
  isSingleNetworkEnabled?: boolean | undefined;
  isCollectedDatasetEnabled?: boolean | undefined;
  isHarmonizedDatasetEnabled?: boolean | undefined;
  style?: string | undefined;
  translations: LocalizedStringDto[];
  isProjectNotificationsEnabled?: boolean | undefined;
  projectNotificationsSubject?: string | undefined;
  portalUrl?: string | undefined;
  availableLayoutOptions: string[];
  searchLayout?: string | undefined;
  maxNumberOfSets: number;
  maxItemsPerSet: number;
  /** legacy */
  anonymousCanCreateCart: boolean;
  currentUserCanCreateCart: boolean;
  currentUserCanCreateSets: boolean;
  isCartEnabled: boolean;
  cartTimeToLive?: number | undefined;
  setTimeToLive?: number | undefined;
  isSetsAnalysisEnabled: boolean;
  isSetsSearchEnabled: boolean;
  downloadOpalViewsFromSetsAllowed: boolean;
  opalViewsGrouping: string;
  signupEnabled?: boolean | undefined;
  signupGroups: string[];
  signupWithPassword: boolean;
  isRepositoryEnabled?: boolean | undefined;
  isDataAccessEnabled?: boolean | undefined;
  variableSummaryRequiresAuthentication?: boolean | undefined;
  isProjectEnabled?: boolean | undefined;
  isUsePublicUrlForSharedLink?: boolean | undefined;
  isImportStudiesFeatureEnabled?: boolean | undefined;
  isVariablesCountEnabled?: boolean | undefined;
  isProjectsCountEnabled?: boolean | undefined;
  isDataAccessRequestsCountEnabled?: boolean | undefined;
  isContingencyEnabled?: boolean | undefined;
  isContactNotificationsEnabled?: boolean | undefined;
  contactNotificationsSubject?: string | undefined;
  contactGroups: string[];
  isCommentsRequiredOnDocumentSave?: boolean | undefined;
  isStudiesCartEnabled: boolean;
  isNetworksCartEnabled: boolean;
  isStudiesCompareEnabled: boolean;
  isNetworksCompareEnabled: boolean;
  maxItemsPerCompare: number;
  isStudiesExportEnabled: boolean;
  isNetworksExportEnabled: boolean;
  usableVariableTaxonomiesForConceptTagging: string[];
  summaryStatisticsAccessPolicy: string;
}

export interface PublicMicaConfigDto {
  name: string;
  openAccess: boolean;
  publicUrl?: string | undefined;
  languages: string[];
  availableLayoutOptions: string[];
  searchLayout?: string | undefined;
  maxNumberOfSets: number;
  maxItemsPerSet: number;
  agateUrl: string;
}

export interface AggregationsConfigDto {
  study: AggregationInfoDto[];
  variable: AggregationInfoDto[];
}

export interface AggregationInfoDto {
  id: string;
  title: LocalizedStringDto[];
}

export interface AttributeDto {
  namespace?: string | undefined;
  name: string;
  values: LocalizedStringDto[];
}

export interface TaxonomyEntityDto {
  name: string;
  titles: LocalizedStringDto[];
  descriptions: LocalizedStringDto[];
}

export interface TermAttributeDto {
  vocabulary: TaxonomyEntityDto | undefined;
  terms: TaxonomyEntityDto[];
}

export interface TermAttributesDto {
  taxonomy: TaxonomyEntityDto | undefined;
  vocabularyTerms: TermAttributeDto[];
}

export interface AnnotationDto {
  taxonomy: string;
  vocabulary: string;
  value: string;
}

export interface DatasetDto {
  id?: string | undefined;
  name: LocalizedStringDto[];
  acronym: LocalizedStringDto[];
  description: LocalizedStringDto[];
  entityType: string;
  published?: boolean | undefined;
  attributes: AttributeDto[];
  timestamps?: TimestampsDto | undefined;
  variableType?: string | undefined;
  permissions?: PermissionsDto | undefined;
  content?: string | undefined;
  state?: EntityStateDto | undefined;
  /** Specific to search */
  countStats?: CountStatsDto | undefined;
  collected?: CollectedDatasetDto | undefined;
  protocol?: HarmonizedDatasetDto | undefined;
}

export interface DatasetDto_StudyTableDto {
  project?: string | undefined;
  table?: string | undefined;
  name: LocalizedStringDto[];
  description: LocalizedStringDto[];
  studyId: string;
  populationId?: string | undefined;
  dataCollectionEventId?: string | undefined;
  dceId?: string | undefined;
  studySummary?: StudySummaryDto | undefined;
  weight?: number | undefined;
  additionalInformation: LocalizedStringDto[];
  source?: string | undefined;
  tableUid?: string | undefined;
}

export interface DatasetDto_HarmonizationTableDto {
  project?: string | undefined;
  table?: string | undefined;
  name: LocalizedStringDto[];
  description: LocalizedStringDto[];
  studyId: string;
  studySummary?: StudySummaryDto | undefined;
  weight?: number | undefined;
  additionalInformation: LocalizedStringDto[];
  source?: string | undefined;
  tableUid?: string | undefined;
}

export interface CollectedDatasetDto {
  studyTable: DatasetDto_StudyTableDto | undefined;
}

export interface HarmonizedDatasetDto {
  harmonizationTable: DatasetDto_HarmonizationTableDto | undefined;
  studyTables: DatasetDto_StudyTableDto[];
  harmonizationTables: DatasetDto_HarmonizationTableDto[];
  networkId?: string | undefined;
}

export interface DatasetsDto {
  total: number;
  from: number;
  limit: number;
  datasets: DatasetDto[];
}

export interface DatasetCategoryDto {
  name: string;
  missing: boolean;
  attributes: AttributeDto[];
}

export interface DatasetVariableDto {
  id: string;
  datasetId: string;
  studyId: string;
  variableType: string;
  name: string;
  entityType: string;
  valueType: string;
  mimeType?: string | undefined;
  repeatable: boolean;
  occurrenceGroup?: string | undefined;
  unit?: string | undefined;
  referencedEntityType?: string | undefined;
  nature: string;
  index: number;
  attributes: AttributeDto[];
  categories: DatasetCategoryDto[];
  datasetName: LocalizedStringDto[];
  studySummary?: StudySummaryDto | undefined;
  termAttributes: TermAttributesDto[];
  networkSummaries: NetworkSummaryDto[];
}

export interface DatasetVariablesDto {
  total: number;
  from: number;
  limit: number;
  variables: DatasetVariableDto[];
}

export interface DatasetVariableResolverDto {
  id: string;
  datasetId: string;
  name: string;
  variableType: string;
  studyId?: string | undefined;
  project?: string | undefined;
  table?: string | undefined;
  datasetName: LocalizedStringDto[];
  datasetAcronym: LocalizedStringDto[];
  variableLabel: LocalizedStringDto[];
  studyName: LocalizedStringDto[];
  studyAcronym: LocalizedStringDto[];
  networkId?: string | undefined;
  networkName: LocalizedStringDto[];
  networkAcronym: LocalizedStringDto[];
  networkTableId?: string | undefined;
  populationId?: string | undefined;
  dceId?: string | undefined;
  annotations: AnnotationDto[];
  valueType?: string | undefined;
  nature?: string | undefined;
  mimeType?: string | undefined;
  repeatable?: boolean | undefined;
  occurrenceGroup?: string | undefined;
  unit?: string | undefined;
  referencedEntityType?: string | undefined;
  categories: DatasetCategoryDto[];
  description: LocalizedStringDto[];
  populationName: LocalizedStringDto[];
  dceName: LocalizedStringDto[];
  entityType?: string | undefined;
  source?: string | undefined;
}

export interface DatasetVariableSummaryDto {
  resolver: DatasetVariableResolverDto | undefined;
  attributes: AttributeDto[];
  studyTable?: DatasetDto_StudyTableDto | undefined;
  harmonizationStudyTable?: DatasetDto_HarmonizationTableDto | undefined;
}

export interface DatasetVariableHarmonizationDto {
  resolver: DatasetVariableResolverDto | undefined;
  datasetVariableSummaries: DatasetVariableSummaryDto[];
}

export interface DatasetVariablesHarmonizationsDto {
  total: number;
  from: number;
  limit: number;
  variableHarmonizations: DatasetVariableHarmonizationDto[];
}

export interface DatasetHarmonizedVariableSummaryDto {
  /** harmonized variable Mlstr_harmo.status */
  status?: string | undefined;
  /** harmonized variable reference (might not exists) */
  harmonizedVariableRef?: DatasetVariableResolverDto | undefined;
  /** harmonized variable Mlstr_harmo.status_detail */
  statusDetail?: string | undefined;
}

export interface DatasetVariableHarmonizationSummaryDto {
  /** dataschema variable reference */
  dataschemaVariableRef: DatasetVariableResolverDto | undefined;
  /** harmonized variables */
  harmonizedVariables: DatasetHarmonizedVariableSummaryDto[];
}

export interface DatasetVariablesHarmonizationSummaryDto {
  total: number;
  from: number;
  limit: number;
  /** columns */
  studyTable: DatasetDto_StudyTableDto[];
  harmonizationStudyTable: DatasetDto_HarmonizationTableDto[];
  /** rows */
  variableHarmonizations: DatasetVariableHarmonizationSummaryDto[];
}

export interface FrequencyDto {
  value: string;
  count: number;
  missing?: boolean | undefined;
}

export interface IntervalFrequencyDto {
  count: number;
  lower: number;
  upper: number;
}

export interface StatisticsDto {
  sum?: number | undefined;
  min?: number | undefined;
  max?: number | undefined;
  mean?: number | undefined;
  sumOfSquares?: number | undefined;
  variance?: number | undefined;
  stdDeviation?: number | undefined;
}

export interface DatasetVariableAggregationDto {
  studyTable?: DatasetDto_StudyTableDto | undefined;
  total: number;
  n: number;
  frequencies: FrequencyDto[];
  statistics?: StatisticsDto | undefined;
  term?: string | undefined;
  missing?: boolean | undefined;
  harmonizationStudyTable?: DatasetDto_HarmonizationTableDto | undefined;
  intervalFrequencies: IntervalFrequencyDto[];
}

export interface DatasetVariableAggregationsDto {
  aggregations: DatasetVariableAggregationDto[];
  total: number;
  n: number;
  frequencies: FrequencyDto[];
  statistics?: StatisticsDto | undefined;
}

export interface DatasetVariableContingencyDto {
  studyTable?: DatasetDto_StudyTableDto | undefined;
  aggregations: DatasetVariableAggregationDto[];
  all?: DatasetVariableAggregationDto | undefined;
  privacyThreshold?: number | undefined;
  harmonizationStudyTable?: DatasetDto_HarmonizationTableDto | undefined;
}

export interface DatasetVariableContingenciesDto {
  contingencies: DatasetVariableContingencyDto[];
  all?: DatasetVariableContingencyDto | undefined;
}

export interface CommentDto {
  id?: string | undefined;
  message: string;
  resourceId: string;
  instanceId: string;
  createdBy: string;
  modifiedBy?: string | undefined;
  timestamps: TimestampsDto | undefined;
  actions: string[];
  createdByProfile?: UserProfileDto | undefined;
  modifiedByProfile?: UserProfileDto | undefined;
  admin?: boolean | undefined;
}

export interface ProjectsDto {
  total: number;
  from: number;
  limit: number;
  projects: ProjectDto[];
  actions: string[];
}

export interface DataAccessRequestDto {
  id?: string | undefined;
  timestamps?: TimestampsDto | undefined;
  applicant: string;
  status: string;
  title?: string | undefined;
  content?: string | undefined;
  attachments: AttachmentDto[];
  actions: string[];
  nextStatus: string[];
  statusChangeHistory: DataAccessRequestDto_StatusChangeDto[];
  profile?: UserProfileDto | undefined;
  project?: ProjectSummaryDto | undefined;
  actionLogHistory: DataAccessRequestDto_ActionLogDto[];
  amendmentsSummary?: DataAccessRequestDto_AmendmentsSummaryDto | undefined;
  startDate?: string | undefined;
  reportsTimeline?: TimelineDto | undefined;
  archived?: boolean | undefined;
  formRevision?: number | undefined;
  type: DataAccessRequestDto_Type;
  parentId?: string | undefined;
}

export enum DataAccessRequestDto_Type {
  REQUEST = 'REQUEST',
  AMENDMENT = 'AMENDMENT',
  FEASIBILITY = 'FEASIBILITY',
  AGREEMENT = 'AGREEMENT',
  PRELIMINARY = 'PRELIMINARY',
  UNRECOGNIZED = 'UNRECOGNIZED',
}

export interface DataAccessRequestDto_ActionLogDto {
  action: string;
  author: string;
  changedOn: string;
  profile?: UserProfileDto | undefined;
}

export interface DataAccessRequestDto_StatusChangeDto {
  from: string;
  to: string;
  author: string;
  changedOn: string;
  profile?: UserProfileDto | undefined;
  reference?: string | undefined;
}

export interface DataAccessRequestDto_AmendmentsSummaryDto {
  id: string;
  pending: number;
  total: number;
  lastModifiedDate?: string | undefined;
}

export interface DataAccessCollaboratorDto {
  requestId: string;
  email: string;
  invitationPending: boolean;
  createdBy: string;
  modifiedBy?: string | undefined;
  timestamps: TimestampsDto | undefined;
}

export interface TimelineDto {
  startDate: string;
  endDate: string;
  intermediateDates: string[];
}

export interface DataAccessRequestSummaryDto {
  id: string;
  status: string;
  viewable: boolean;
  applicant?: string | undefined;
}

export interface ProjectSummaryDto {
  id: string;
  permissions?: PermissionsDto | undefined;
}

export interface ProjectDto {
  id?: string | undefined;
  timestamps?: TimestampsDto | undefined;
  title: LocalizedStringDto[];
  summary: LocalizedStringDto[];
  content?: string | undefined;
  request?: DataAccessRequestSummaryDto | undefined;
  permissions?: PermissionsDto | undefined;
  published?: boolean | undefined;
  state?: EntityStateDto | undefined;
}

export interface LocalizedPropertyDto {
  name: string;
  value: LocalizedStringDto[];
}

export interface DataAccessConfigDto {
  idPrefix?: string | undefined;
  idLength: number;
  notifySubmitted: boolean;
  notifyReviewed: boolean;
  notifyApproved: boolean;
  notifyRejected: boolean;
  notifyReopened: boolean;
  notifyCommented: boolean;
  withReview: boolean;
  approvedFinal: boolean;
  rejectedFinal: boolean;
  submittedSubject?: string | undefined;
  reviewedSubject?: string | undefined;
  approvedSubject?: string | undefined;
  rejectedSubject?: string | undefined;
  reopenedSubject?: string | undefined;
  commentedSubject?: string | undefined;
  notifyConditionallyApproved: boolean;
  withConditionalApproval: boolean;
  conditionallyApprovedSubject?: string | undefined;
  notifyAttachment: boolean;
  attachmentSubject?: string | undefined;
  predefinedActions: string[];
  amendmentsEnabled: boolean;
  daoCanEdit: boolean;
  allowIdWithLeadingZeros?: boolean | undefined;
  notifyCreated: boolean;
  createdSubject?: string | undefined;
  notifyFinalReport: boolean;
  finalReportSubject?: string | undefined;
  notifyIntermediateReport: boolean;
  intermediateReportSubject?: string | undefined;
  nbOfDaysBeforeReport?: number | undefined;
  feasibilityEnabled: boolean;
  variablesEnabled: boolean;
  feasibilityVariablesEnabled: boolean;
  amendmentVariablesEnabled: boolean;
  csvExportFormat?: string | undefined;
  feasibilityCsvExportFormat?: string | undefined;
  amendmentCsvExportFormat?: string | undefined;
  collaboratorsEnabled: boolean;
  collaboratorInvitationDays?: number | undefined;
  collaboratorInvitationSubject?: string | undefined;
  notifyCollaboratorAccepted: boolean;
  collaboratorAcceptedSubject?: string | undefined;
  agreementEnabled: boolean;
  preliminaryEnabled: boolean;
  preliminaryVariablesEnabled: boolean;
  preliminaryCsvExportFormat?: string | undefined;
  mergePreliminaryContentEnabled: boolean;
  agreementOpenedPolicy: string;
  randomId: boolean;
}

export interface DataAccessFormDto {
  schema: string;
  definition: string;
  pdfTemplates: AttachmentDto[];
  properties: LocalizedPropertyDto[];
  titleFieldPath?: string | undefined;
  summaryFieldPath?: string | undefined;
  pdfDownloadType: DataAccessFormDto_PdfDownloadType;
  endDateFieldPath?: string | undefined;
  revision?: number | undefined;
  lastUpdateDate?: string | undefined;
}

export enum DataAccessFormDto_PdfDownloadType {
  Template = 'Template',
  Embedded = 'Embedded',
  UNRECOGNIZED = 'UNRECOGNIZED',
}

export interface DataAccessPreliminaryFormDto {
  schema: string;
  definition: string;
  revision?: number | undefined;
  lastUpdateDate?: string | undefined;
}

export interface DataAccessFeasibilityFormDto {
  schema: string;
  definition: string;
  revision?: number | undefined;
  lastUpdateDate?: string | undefined;
}

export interface DataAccessAgreementFormDto {
  schema: string;
  definition: string;
  revision?: number | undefined;
  lastUpdateDate?: string | undefined;
}

export interface DataAccessAmendmentFormDto {
  schema: string;
  definition: string;
  properties: LocalizedPropertyDto[];
  titleFieldPath?: string | undefined;
  summaryFieldPath?: string | undefined;
  withReview: boolean;
  approvedFinal: boolean;
  endDateFieldPath?: string | undefined;
  revision?: number | undefined;
  lastUpdateDate?: string | undefined;
}

export interface ProjectFormDto {
  schema: string;
  definition: string;
  properties: LocalizedPropertyDto[];
}

export interface EntityFormDto {
  type: EntityFormDto_Type;
  schema: string;
  definition: string;
}

export enum EntityFormDto_Type {
  Network = 'Network',
  Study = 'Study',
  Population = 'Population',
  DataCollectionEvent = 'DataCollectionEvent',
  CollectedDataset = 'CollectedDataset',
  HarmonizedDataset = 'HarmonizedDataset',
  HarmonizationStudy = 'HarmonizationStudy',
  UNRECOGNIZED = 'UNRECOGNIZED',
}

export interface UserProfileDto {
  username: string;
  groups: string[];
  attributes: UserProfileDto_AttributeDto[];
}

export interface UserProfileDto_AttributeDto {
  key: string;
  value?: string | undefined;
}

export interface GitCommitInfoDto {
  author: string;
  date: string;
  comment: string;
  commitId: string;
  diffEntries: string[];
  blob?: string | undefined;
  /** head of the commit tree */
  isHead?: boolean | undefined;
  /** current (latest) commit for a given path */
  isCurrent?: boolean | undefined;
}

export interface FileDto {
  name: string;
  path: string;
  type: FileType;
  children: FileDto[];
  size?: number | undefined;
  timestamps?: TimestampsDto | undefined;
  state?: AttachmentStateDto | undefined;
  attachment?: AttachmentDto | undefined;
  revisionStatus?: string | undefined;
  permissions?: PermissionsDto | undefined;
  mediaType?: string | undefined;
  description: LocalizedStringDto[];
}

export interface AttachmentStateDto {
  id: string;
  name: string;
  path: string;
  timestamps?: TimestampsDto | undefined;
  attachment?: AttachmentDto | undefined;
  publishedId?: string | undefined;
  publicationDate?: string | undefined;
  publishedBy?: string | undefined;
  revisions: AttachmentDto[];
}

export interface MicaMetricsDto {
  documents: MicaMetricsDto_DocumentMetricsDto[];
}

export interface MicaMetricsDto_DocumentMetricsDto {
  type: string;
  properties: MicaMetricsDto_PropertyDto[];
}

export interface MicaMetricsDto_PropertyDto {
  name: string;
  value?: number | undefined;
}

export interface DocumentSetDto {
  id: string;
  type: string;
  name?: string | undefined;
  timestamps?: TimestampsDto | undefined;
  username?: string | undefined;
  identifiers: string[];
  count: number;
  locked: boolean;
}

export interface ComposedSetDto {
  id: string;
  type: string;
  name?: string | undefined;
  timestamps?: TimestampsDto | undefined;
  username?: string | undefined;
  operation: string;
  sets: string[];
  query: string;
  count: number;
}

export interface SetOperationDto {
  id: string;
  type: string;
  sets: string[];
  compositions: ComposedSetDto[];
}

export interface EntityIndexHealthDto {
  requireIndexing: EntityIndexHealthDto_ItemDto[];
}

export interface EntityIndexHealthDto_ItemDto {
  id: string;
  title: LocalizedStringDto[];
}

export interface CountStatsDto {
  variables?: number | undefined;
  studyDatasets?: number | undefined;
  harmonizationDatasets?: number | undefined;
  studies?: number | undefined;
  individualStudies?: number | undefined;
  harmonizationStudies?: number | undefined;
  networks?: number | undefined;
  studyVariables?: number | undefined;
  dataschemaVariables?: number | undefined;
  studiesWithVariables?: number | undefined;
  harmonizationStudiesWithVariables?: number | undefined;
}
