// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v3.21.12
// source: MicaPlugins.proto

export const protobufPackage = 'obiba.mica';

export enum ServicePluginStatus {
  RUNNING = 'RUNNING',
  STOPPED = 'STOPPED',
  UNRECOGNIZED = 'UNRECOGNIZED',
}

export interface PluginPackageDto {
  name: string;
  title: string;
  description: string;
  author: string;
  maintainer: string;
  license: string;
  website?: string | undefined;
  version: string;
  micaVersion: string;
  type: string;
  file?: string | undefined;
  uninstalled?: boolean | undefined;
}

export interface PluginPackagesDto {
  site: string;
  updated?: string | undefined;
  restart: boolean;
  packages: PluginPackageDto[];
}

export interface PluginDto {
  name: string;
  title: string;
  description: string;
  author: string;
  maintainer: string;
  license: string;
  website?: string | undefined;
  version: string;
  micaVersion: string;
  type: string;
  siteProperties: string;
}

export interface ServicePluginDto {
  name: string;
  status: ServicePluginStatus;
}
