// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v3.21.12
// source: MicaSearch.proto

import type {
  DatasetDto,
  DatasetVariableDto,
  DatasetVariableResolverDto,
  DocumentDigestDto,
  LocalizedStringDto,
  NetworkDto,
  StudyDto,
  StudySummaryDto,
  TaxonomyEntityDto,
} from "./Mica";

export const protobufPackage = "obiba.mica";

export interface JoinQueryResultDto {
  variableResultDto?: QueryResultDto | undefined;
  datasetResultDto?: QueryResultDto | undefined;
  studyResultDto?: QueryResultDto | undefined;
  networkResultDto?: QueryResultDto | undefined;
}

export interface QueryResultDto {
  aggs: AggregationResultDto[];
  totalHits: number;
  totalCount: number;
  variableResult?: DatasetVariableResultDto | undefined;
  datasetResult?: DatasetResultDto | undefined;
  studyResult?: StudyResultDto | undefined;
  networkResult?: NetworkResultDto | undefined;
  summaries: StudySummaryDto[];
}

export interface DatasetVariableResultDto {
  summaries: DatasetVariableResolverDto[];
  variables: DatasetVariableDto[];
  datasets: DatasetDto[];
}

export interface DatasetResultDto {
  datasets: DatasetDto[];
  digests: DocumentDigestDto[];
}

export interface StudyResultDto {
  summaries: StudySummaryDto[];
  studies: StudyDto[];
  digests: DocumentDigestDto[];
}

export interface NetworkResultDto {
  networks: NetworkDto[];
  digests: DocumentDigestDto[];
}

export interface AggregationResultDto {
  aggregation: string;
  title: LocalizedStringDto[];
  children: AggregationResultDto[];
  terms: TermsAggregationResultDto[];
  stats?: StatsAggregationResultDto | undefined;
  ranges: RangeAggregationResultDto[];
}

export interface TermsAggregationResultDto {
  key: string;
  title?: string | undefined;
  description?: string | undefined;
  className?: string | undefined;
  count: number;
  aggs: AggregationResultDto[];
  start?: string | undefined;
  end?: string | undefined;
  sortField?: string | undefined;
}

export interface StatsAggregationResultDataDto {
  count: number;
  min?: number | undefined;
  max?: number | undefined;
  avg?: number | undefined;
  sum?: number | undefined;
}

export interface StatsAggregationResultDto {
  data: StatsAggregationResultDataDto | undefined;
}

export interface RangeAggregationResultDto {
  key: string;
  title?: string | undefined;
  description?: string | undefined;
  className?: string | undefined;
  default: number;
  count: number;
  from?: number | undefined;
  to?: number | undefined;
  aggs: AggregationResultDto[];
}

export interface BucketCoverageDto {
  field: string;
  value: string;
  hits: number;
  count?: number | undefined;
  title?: string | undefined;
  description?: string | undefined;
  className?: string | undefined;
  start?: string | undefined;
  end?: string | undefined;
  sortField?: string | undefined;
}

export interface TermCoverageDto {
  term: TaxonomyEntityDto | undefined;
  hits: number;
  buckets: BucketCoverageDto[];
}

export interface VocabularyCoverageDto {
  vocabulary: TaxonomyEntityDto | undefined;
  hits: number;
  /** sum of the hits of vocabulary allows multiple terms */
  count?: number | undefined;
  buckets: BucketCoverageDto[];
  terms: TermCoverageDto[];
}

export interface TaxonomyCoverageDto {
  taxonomy: TaxonomyEntityDto | undefined;
  hits: number;
  buckets: BucketCoverageDto[];
  vocabularies: VocabularyCoverageDto[];
}

export interface TaxonomiesCoverageDto {
  taxonomies: TaxonomyCoverageDto[];
  totalHits: number;
  totalCount: number;
  by: string[];
  queryResult?: JoinQueryResultDto | undefined;
}

export interface BucketsCoverageDto {
  taxonomyHeaders: BucketsCoverageDto_HeaderDto[];
  vocabularyHeaders: BucketsCoverageDto_HeaderDto[];
  termHeaders: BucketsCoverageDto_HeaderDto[];
  rows: BucketsCoverageDto_RowDto[];
  totalCounts?: EntitiesTotalCountsDto | undefined;
}

export interface BucketsCoverageDto_HeaderDto {
  entity: TaxonomyEntityDto | undefined;
  hits: number;
  termsCount: number;
}

export interface BucketsCoverageDto_RowDto {
  field: string;
  value: string;
  title?: string | undefined;
  description?: string | undefined;
  className?: string | undefined;
  hits: number[];
  counts: number[];
  start?: string | undefined;
  end?: string | undefined;
  sortField?: string | undefined;
}

export interface ChartsCoverageDto {
  charts: ChartsCoverageDto_ChartDto[];
}

export interface ChartsCoverageDto_ChartDataItemDto {
  key: string;
  value: number;
  title: string;
}

export interface ChartsCoverageDto_ChartTermDataDto {
  term: string;
  items: ChartsCoverageDto_ChartDataItemDto[];
}

export interface ChartsCoverageDto_ChartDataDto {
  vocabulary: string;
  items: ChartsCoverageDto_ChartDataItemDto[];
  termItems: ChartsCoverageDto_ChartTermDataDto[];
}

export interface ChartsCoverageDto_ChartDto {
  title: string;
  subtitle?: string | undefined;
  taxonomy: string;
  data: ChartsCoverageDto_ChartDataDto[];
}

export interface VariableEntitiesCountDto {
  query: string;
  variable: DocumentDigestDto | undefined;
  count: number;
  studyTableName: LocalizedStringDto[];
}

export interface DatasetEntitiesCountDto {
  dataset: DocumentDigestDto | undefined;
  counts: VariableEntitiesCountDto[];
}

export interface StudyEntitiesCountDto {
  entityType: string;
  /** original query restricted to study variables */
  query: string;
  study:
    | DocumentDigestDto
    | undefined;
  /** all criteria count */
  total: number;
  belowPrivacyThreshold: boolean;
  counts: DatasetEntitiesCountDto[];
}

export interface EntitiesCountDto {
  /** original query */
  query: string;
  /** sum of the study counts */
  total: number;
  belowPrivacyThreshold: boolean;
  counts: StudyEntitiesCountDto[];
}

export interface EntityTotalCountDto {
  total: number;
  hits: number;
}

export interface EntitiesTotalCountsDto {
  studyTotalCount?: EntityTotalCountDto | undefined;
  datasetTotalCount?: EntityTotalCountDto | undefined;
  variableTotalCount?: EntityTotalCountDto | undefined;
  networkTotalCount?: EntityTotalCountDto | undefined;
}
