// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v3.21.12
// source: MicaSecurity.proto

export const protobufPackage = 'obiba.mica';

export interface AclDto {
  type: string;
  principal: string;
  resource: string;
  role?: string | undefined;
  instance?: string | undefined;
  otherResources: string[];
  file?: boolean | undefined;
}
