services:
        es8:
                #image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION}
                image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
                ports:
                  - 9300:9300
                  - 9200:9200
                environment:
                        - cluster.name=mica
                        - node.name=es8
                        - discovery.type=single-node
                        - bootstrap.memory_lock=true
                        - network.host=0.0.0.0
                        - xpack.security.enabled=false
                        - xpack.security.http.ssl.enabled=false
                        - ES_JAVA_OPTS=-Xms512m -Xmx512m
                ulimits:
                        memlock:
                                soft: -1
                                hard: -1
