#! /usr/bin/env python
#
import argparse

import mica.file
import mica.rest
import mica.import_zip
import mica.perm_network
import mica.perm_project
import mica.perm_individual_study
import mica.perm_harmonization_study
import mica.perm_collected_dataset
import mica.perm_harmonized_dataset
import mica.access_network
import mica.access_project
import mica.access_individual_study
import mica.access_harmonization_study
import mica.access_collected_dataset
import mica.access_harmonized_dataset
import mica.access_file
import mica.search
import mica.tags
import mica.update_collected_dataset
import mica.update_collected_datasets

def add_mica_arguments(parser):
    """
    Add Mica access arguments
    """
    parser.add_argument('--mica', '-mk', required=False, default='http://localhost:8082', help='Mica server base url (default: http://localhost:8082)')
    parser.add_argument('--user', '-u', required=False, help='User name')
    parser.add_argument('--password', '-p', required=False, help='User password')
    parser.add_argument('--verbose', '-v', action='store_true', help='Verbose output')


def add_subcommand(name, help, add_args_func, default_func):
    """
    Make a sub-parser, add default arguments to it, add sub-command arguments and set the sub-command callback function.
    """
    subparser = subparsers.add_parser(name, help=help)
    add_mica_arguments(subparser)
    add_args_func(subparser)
    subparser.set_defaults(func=default_func)


# Parse arguments
parser = argparse.ArgumentParser(description='Mica command line.')
subparsers = parser.add_subparsers(title='sub-commands',
                                   help='Available sub-commands. Use --help option on the sub-command '
                                        'for more details.')

# Add subcommands
add_subcommand('import-zip', 'Import data from zip file(s) that have been extracted from old Mica',
               mica.import_zip.add_arguments, mica.import_zip.do_command)
add_subcommand('file', 'Mica file system actions, for advanced users.', mica.file.add_arguments,
               mica.file.do_command)

add_subcommand('perm-network', 'Apply permission on a network.',
               mica.perm_network.add_arguments, mica.perm_network.do_command)
add_subcommand('perm-project', 'Apply permission on a research project.',
               mica.perm_project.add_arguments, mica.perm_project.do_command)
add_subcommand('perm-individual-study', 'Apply permission on an individual study.',
               mica.perm_individual_study.add_arguments, mica.perm_individual_study.do_command)
add_subcommand('perm-harmonization-study', 'Apply permission on a harmonization study.',
               mica.perm_harmonization_study.add_arguments, mica.perm_harmonization_study.do_command)
add_subcommand('perm-collected-dataset', 'Apply permission on a collected dataset.',
               mica.perm_collected_dataset.add_arguments, mica.perm_collected_dataset.do_command)
add_subcommand('perm-harmonized-dataset', 'Apply permission on a harmonized dataset.',
               mica.perm_harmonized_dataset.add_arguments, mica.perm_harmonized_dataset.do_command)

add_subcommand('access-network', 'Apply access on a network.',
               mica.access_network.add_arguments, mica.access_network.do_command)
add_subcommand('access-project', 'Apply access on a research project.',
               mica.access_project.add_arguments, mica.access_project.do_command)
add_subcommand('access-individual-study', 'Apply access on an individual study.',
               mica.access_individual_study.add_arguments, mica.access_individual_study.do_command)
add_subcommand('access-harmonization-study', 'Apply access on a harmonization study.',
               mica.access_harmonization_study.add_arguments, mica.access_harmonization_study.do_command)
add_subcommand('access-collected-dataset', 'Apply access on a collected dataset.',
               mica.access_collected_dataset.add_arguments, mica.access_collected_dataset.do_command)
add_subcommand('access-harmonized-dataset', 'Apply access on a harmonized dataset.',
               mica.access_harmonized_dataset.add_arguments, mica.access_harmonized_dataset.do_command)
add_subcommand('access-file', 'Apply access on a file.',
               mica.access_file.add_arguments, mica.access_file.do_command)

add_subcommand('search', 'Perform a search query on variables, datasets, studies (including populations and data collection events) and networks.', mica.search.add_arguments,
               mica.search.do_command)

add_subcommand('tags', 'Extract classification tags from published variables.', mica.tags.add_arguments,
               mica.tags.do_command)

add_subcommand('update-collected-dataset', 'Update collected dataset linkage with an Opal table.', mica.update_collected_dataset.add_arguments,
               mica.update_collected_dataset.do_command)
add_subcommand('update-collected-datasets', 'Update collected datasets linkage with an Opal table.', mica.update_collected_datasets.add_arguments,
               mica.update_collected_datasets.do_command)

add_subcommand('rest', 'Request directly the Mica REST API, for advanced users.', mica.rest.add_arguments,
               mica.rest.do_command)

# Execute selected command
args = parser.parse_args()
args.func(args)
